#!/bin/bash
#SBATCH --job-name="sft-mix5ds"
#SBATCH --account=pgs
#SBATCH --qos=low
#SBATCH --partition=gemini
#SBATCH -o out/%j-%x.out
#SBATCH -e out/%j-%x.err
#SBATCH --time=07-00:00:00
#SBATCH --gpus=4
#SBATCH --exclude=CPIIGPU-211-128
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --ntasks-per-node=1

hostname
echo "Job started at: $(date)"
echo "Job ID: $SLURM_JOB_ID"

mkdir -p out

source ~/anaconda3/bin/activate
eval "$(conda shell.bash hook)"
conda activate searchr1
unset HF_HUB_OFFLINE
unset TRANSFORMERS_OFFLINE

cd /mnt/users_home/cpii.local/yli/Ambig-R1-new-claude/code

export WANDB_PROJECT='Ambig-R1'
# Start from Qwen2.5-3B-Instruct (same as the original SFT warmup)
export BASE_MODEL="Qwen/Qwen2.5-3B-Instruct"
export EXPERIMENT_NAME=sft-mix5ds-qwen3-4b
export WANDB_MODE=offline

# SFT data: mix5ds generated by prepare_sft_mix5ds.py
SFT_DATA_DIR=/mnt/users_home/cpii.local/yli/Ambig-R1-new-claude/code/scripts/data_process/data/sft_mix5ds

echo "Base model: $BASE_MODEL"
echo "SFT data: $SFT_DATA_DIR"
echo "Expected: ~50% clarify, ~50% answer from 5 datasets"

# First: generate SFT data
echo ""
echo "===== Step 1: Generate SFT data ====="
python3 ~/Ambig-R1-new/code/scripts/prepare_sft_mix5ds.py \
    --input_parquet ~/Ambig-R1-new-claude/code/scripts/data_process/data/mix_5ds/train.parquet \
    --output_dir "$SFT_DATA_DIR" \
    --n_per_dataset 400 \
    --seed 42 \
    2>&1 | tee sft-mix5ds-prepare.log

echo ""
echo "===== Step 2: SFT Training ====="
# Train 3 epochs, save every 110 steps (roughly 1 epoch)
torchrun --master_port=29500 \
    --nproc_per_node=4 \
    -m verl.trainer.fsdp_sft_trainer \
    data.train_files=$SFT_DATA_DIR/train.parquet \
    data.val_files=$SFT_DATA_DIR/val.parquet \
    data.train_batch_size=32 \
    data.micro_batch_size=4 \
    data.prompt_key=prompt \
    data.response_key=response \
    data.max_length=4096 \
    data.truncation=error \
    data.balance_dp_token=False \
    model.partial_pretrain=$BASE_MODEL \
    model.fsdp_config.wrap_policy.min_num_params=0 \
    model.fsdp_config.cpu_offload=False \
    model.enable_gradient_checkpointing=True \
    model.trust_remote_code=False \
    optim.lr=1e-5 \
    optim.betas='[0.9,0.95]' \
    optim.weight_decay=0.01 \
    optim.warmup_steps_ratio=0.1 \
    optim.clip_grad=1.0 \
    trainer.default_local_dir=verl_checkpoints/$EXPERIMENT_NAME \
    trainer.default_hdfs_dir=null \
    trainer.project_name=$WANDB_PROJECT \
    trainer.experiment_name=$EXPERIMENT_NAME \
    trainer.total_epochs=3 \
    trainer.total_training_steps=null \
    trainer.validate_before_training=True \
    trainer.logger='[console,wandb]' \
    +trainer.save_freq=110 \
    2>&1 | tee sft-mix5ds.log

# ---------- Summary ----------
echo ""
echo "===== SFT Training Complete ====="
echo ""
echo "===== Val Loss Summary ====="
grep -E "val/loss" sft-mix5ds.log | tail -10
echo ""
echo "Checkpoints saved in: verl_checkpoints/$EXPERIMENT_NAME/"
ls -la verl_checkpoints/$EXPERIMENT_NAME/global_step_* 2>/dev/null
echo ""
echo "NEXT STEP: Pick lowest val_loss checkpoint for ATCC training."
echo "Example:"
LATEST_CKPT=$(ls -td verl_checkpoints/$EXPERIMENT_NAME/global_step_* 2>/dev/null | head -1)
if [ -n "$LATEST_CKPT" ]; then
    echo "  Base: $LATEST_CKPT"
fi

echo "Job finished at: $(date)"
